#Fichero: Makefile
#Compilar con:
# $make

main:
	@echo "\n=== Uso: crear o eliminar\n"

crear: 
	@echo "\n=== Crear...\n"
	mkdir curso2
	mkdir curso2/add
	mkdir curso2/sgy
	mkdir curso2/srd
	chmod 700 curso2/*
	@echo "Carpetas creadas!"

eliminar:
	@echo "\n=== Eliminar...\n"
	rm -r curso2
	@echo "Carpetas eliminadas!"
        
